// frontend/src/pages/Settings.tsx
// Settings.tsx — route /settings. Design-ref grouped-card layout: profile,
// appearance (dark switch + language), Design (accent picker), Verwaltung
// (admin), logout, version.
import type { ReactNode } from 'react';
import { useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { api } from '../lib/api';
import { Icon, type IconName } from '../components/Icon';
import { LargeTitleHeader } from '../components/Header';
import { useTheme } from '../hooks/useTheme';
import { useUserStore } from '../stores/userStore';
import { LOCALES, setLocale } from '../lib/i18n';
import { THEMES, THEME_BY_ACCENT } from '../lib/themes';

function Group({ children }: { children: ReactNode }) {
  return (
    <div
      style={{
        background: 'var(--surface-base)',
        border: '1px solid var(--border-subtle)',
        borderRadius: 18,
        overflow: 'hidden',
        boxShadow: 'var(--shadow-sm)',
      }}
    >
      {children}
    </div>
  );
}

function Switch({ on, onToggle }: { on: boolean; onToggle: () => void }) {
  return (
    <button
      onClick={onToggle}
      role="switch"
      aria-checked={on}
      style={{
        width: 50,
        height: 30,
        borderRadius: 20,
        border: 'none',
        cursor: 'pointer',
        padding: 2,
        flexShrink: 0,
        background: on ? 'var(--accent)' : 'var(--border-default)',
        transition: 'background .2s',
        display: 'flex',
        justifyContent: on ? 'flex-end' : 'flex-start',
        alignItems: 'center',
      }}
    >
      <span
        style={{
          width: 26,
          height: 26,
          borderRadius: '50%',
          background: '#fff',
          boxShadow: '0 1px 3px rgba(0,0,0,0.25)',
        }}
      />
    </button>
  );
}

function Row({
  icon,
  iconColor,
  label,
  right,
  onClick,
  last,
}: {
  icon?: IconName;
  iconColor?: string;
  label: string;
  right?: ReactNode;
  onClick?: () => void;
  last?: boolean;
}) {
  return (
    <button
      onClick={onClick}
      style={{
        width: '100%',
        display: 'flex',
        alignItems: 'center',
        gap: 13,
        padding: '14px 16px',
        minHeight: 56,
        background: 'transparent',
        cursor: onClick ? 'pointer' : 'default',
        textAlign: 'left',
        border: 'none',
        borderBottom: last ? 'none' : '1px solid var(--border-subtle)',
      }}
    >
      {icon && (
        <div
          style={{
            width: 32,
            height: 32,
            borderRadius: 9,
            flexShrink: 0,
            display: 'grid',
            placeItems: 'center',
            color: '#fff',
            background: iconColor,
          }}
        >
          <Icon name={icon} size={19} strokeWidth={2} />
        </div>
      )}
      <span style={{ flex: 1, fontSize: 15.5, fontWeight: 500, color: 'var(--text-primary)' }}>
        {label}
      </span>
      {right}
    </button>
  );
}

function SectionLabel({ children }: { children: ReactNode }) {
  return (
    <div
      style={{
        fontSize: 11.5,
        fontWeight: 700,
        letterSpacing: '0.06em',
        textTransform: 'uppercase',
        color: 'var(--text-muted)',
        padding: '0 6px 8px',
      }}
    >
      {children}
    </div>
  );
}

export default function Settings() {
  const { t, i18n } = useTranslation();
  const navigate = useNavigate();
  const { accent, setAccent, dark, toggleDark } = useTheme();
  const user = useUserStore((s) => s.user);
  const themeName = THEME_BY_ACCENT[accent.toLowerCase()]?.name ?? 'Custom';

  const logout = async () => {
    await api.post('/auth/logout', {}).catch(() => {});
    navigate('/login', { replace: true });
  };

  return (
    <div
      style={{
        height: '100%',
        display: 'flex',
        flexDirection: 'column',
        background: 'var(--surface-base)',
      }}
    >
      <LargeTitleHeader title={t('settings.title')} />
      <div className="scroll" style={{ flex: 1, overflowY: 'auto' }}>
        <div
          style={{ display: 'flex', flexDirection: 'column', gap: 16, padding: '4px 16px 24px' }}
        >
          {/* profile */}
          {user && (
            <Group>
              <div style={{ display: 'flex', alignItems: 'center', gap: 14, padding: 16 }}>
                <div
                  style={{
                    width: 54,
                    height: 54,
                    borderRadius: '50%',
                    flexShrink: 0,
                    display: 'grid',
                    placeItems: 'center',
                    color: '#fff',
                    fontFamily: "'Fraunces', serif",
                    fontSize: 24,
                    fontWeight: 600,
                    background: 'linear-gradient(150deg, var(--accent), var(--accent-600))',
                    boxShadow: 'var(--shadow-pop)',
                  }}
                >
                  {user.name.slice(0, 1).toUpperCase()}
                </div>
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                    <span
                      className="ff-display"
                      style={{ fontSize: 19, fontWeight: 600, color: 'var(--text-primary)' }}
                    >
                      {user.name}
                    </span>
                    <span
                      style={{
                        fontSize: 10.5,
                        fontWeight: 700,
                        letterSpacing: '0.04em',
                        textTransform: 'uppercase',
                        color: 'var(--accent)',
                        background: 'var(--accent-light)',
                        borderRadius: 6,
                        padding: '2px 7px',
                      }}
                    >
                      {t(`admin.role_${user.role}`)}
                    </span>
                  </div>
                  <div style={{ fontSize: 13.5, color: 'var(--text-muted)', marginTop: 2 }}>
                    {user.email}
                  </div>
                </div>
                <Icon name="chevron-right" size={18} style={{ color: 'var(--text-muted)' }} />
              </div>
            </Group>
          )}

          {/* appearance */}
          <Group>
            <Row
              icon="moon"
              iconColor="#6366f1"
              label={t('settings.dark_mode')}
              right={<Switch on={dark} onToggle={toggleDark} />}
            />
            <div style={{ padding: '14px 16px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 13, marginBottom: 12 }}>
                <div
                  style={{
                    width: 32,
                    height: 32,
                    borderRadius: 9,
                    flexShrink: 0,
                    display: 'grid',
                    placeItems: 'center',
                    color: '#fff',
                    background: '#0ea5e9',
                  }}
                >
                  <Icon name="globe" size={19} strokeWidth={2} />
                </div>
                <span
                  style={{ flex: 1, fontSize: 15.5, fontWeight: 500, color: 'var(--text-primary)' }}
                >
                  {t('settings.language')}
                </span>
              </div>
              <div style={{ display: 'flex', gap: 6 }}>
                {LOCALES.map((l) => {
                  const on = i18n.language === l.code;
                  return (
                    <button
                      key={l.code}
                      onClick={() => setLocale(l.code)}
                      style={{
                        flex: 1,
                        fontSize: 13.5,
                        fontWeight: 600,
                        padding: '9px 4px',
                        borderRadius: 11,
                        cursor: 'pointer',
                        border: `1px solid ${on ? 'var(--accent)' : 'var(--border-subtle)'}`,
                        background: on ? 'var(--accent-light)' : 'var(--surface-raised)',
                        color: on ? 'var(--accent)' : 'var(--text-secondary)',
                      }}
                    >
                      {l.label}
                    </button>
                  );
                })}
              </div>
            </div>
          </Group>

          {/* design / accent */}
          <div>
            <SectionLabel>Design</SectionLabel>
            <Group>
              <div style={{ padding: 16 }}>
                <div
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'space-between',
                    marginBottom: 15,
                  }}
                >
                  <span style={{ fontSize: 15.5, fontWeight: 500, color: 'var(--text-primary)' }}>
                    Akzentfarbe
                  </span>
                  <span style={{ fontSize: 13.5, fontWeight: 600, color: 'var(--accent)' }}>
                    {themeName}
                  </span>
                </div>
                <div style={{ display: 'flex', gap: 8, justifyContent: 'space-between' }}>
                  {THEMES.map((th) => {
                    const on = accent.toLowerCase() === th.accent.toLowerCase();
                    return (
                      <button
                        key={th.id}
                        onClick={() => setAccent(th.accent)}
                        aria-label={th.name}
                        style={{
                          width: 46,
                          height: 46,
                          borderRadius: '50%',
                          cursor: 'pointer',
                          flexShrink: 0,
                          padding: 3,
                          background: 'transparent',
                          display: 'grid',
                          placeItems: 'center',
                          border: `2.5px solid ${on ? th.accent : 'transparent'}`,
                        }}
                      >
                        <span
                          style={{
                            width: '100%',
                            height: '100%',
                            borderRadius: '50%',
                            display: 'grid',
                            placeItems: 'center',
                            color: '#fff',
                            background: `linear-gradient(150deg, ${th.accent}, ${th.accent600})`,
                            boxShadow: on
                              ? `0 4px 12px color-mix(in oklab, ${th.accent} 45%, transparent)`
                              : 'none',
                          }}
                        >
                          {on && <Icon name="check" size={19} strokeWidth={3} />}
                        </span>
                      </button>
                    );
                  })}
                </div>
              </div>
            </Group>
          </div>

          {/* admin */}
          {user?.role === 'admin' && (
            <div>
              <SectionLabel>Verwaltung</SectionLabel>
              <Group>
                <Row
                  icon="users"
                  iconColor="#3b82f6"
                  label={t('admin.users_title')}
                  onClick={() => navigate('/admin/users')}
                  right={
                    <Icon name="chevron-right" size={18} style={{ color: 'var(--text-muted)' }} />
                  }
                />
                <Row
                  icon="box"
                  iconColor="#f59e0b"
                  label={t('admin.products_title')}
                  onClick={() => navigate('/admin/products')}
                  last
                  right={
                    <Icon name="chevron-right" size={18} style={{ color: 'var(--text-muted)' }} />
                  }
                />
              </Group>
            </div>
          )}

          {/* logout */}
          <Group>
            <button
              onClick={logout}
              style={{
                width: '100%',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                gap: 9,
                padding: 15,
                minHeight: 54,
                cursor: 'pointer',
                background: 'transparent',
                border: 'none',
                color: '#ef4444',
                fontSize: 15.5,
                fontWeight: 600,
              }}
            >
              <Icon name="logout" size={19} strokeWidth={2} />
              {t('settings.logout')}
            </button>
          </Group>

          <div
            style={{
              textAlign: 'center',
              fontSize: 12,
              color: 'var(--text-muted)',
              padding: '4px 0',
            }}
          >
            TanteEmma · Version 1.0
          </div>
        </div>
      </div>
    </div>
  );
}

// frontend/src/routes/settings/+page.svelte
<script lang="ts">
	import { browser } from '$app/environment';
	import { locale, _ } from 'svelte-i18n';
	import { user } from '$lib/stores/userStore';
	import { theme as themeStore } from '$lib/stores/themeStore';
	import { api } from '$lib/api';
	import { goto } from '$app/navigation';

	const LOCALES = [
		{ code: 'de', label: 'Deutsch' },
		{ code: 'en', label: 'English' },
		{ code: 'pt-BR', label: 'Português (BR)' }
	];

	const darkMode = $derived($themeStore === 'dark');

	function toggleDark() {
		themeStore.set($themeStore === 'dark' ? 'light' : 'dark');
	}

	function setLocale(code: string) {
		locale.set(code);
		if (browser) localStorage.setItem('locale', code);
	}

	async function logout() {
		await api.post('/auth/logout', {});
		goto('/login', { replaceState: true });
	}
</script>

<main class="page">
	<header class="page-header">
		<h1>{$_('settings.title')}</h1>
	</header>

	{#if $user}
		<section class="profile-card">
			<div class="avatar">{$user.name[0]?.toUpperCase()}</div>
			<div class="profile-info">
				<p class="profile-name">{$user.name}</p>
				<p class="profile-email">{$user.email}</p>
				<span class="role-badge">{$user.role}</span>
			</div>
		</section>
	{/if}

	<section class="settings-section">
		<div class="setting-row">
			<span class="setting-label">{$_('settings.dark_mode')}</span>
			<button
				class="toggle"
				class:on={darkMode}
				onclick={toggleDark}
				role="switch"
				aria-checked={darkMode}
				aria-label={$_('settings.dark_mode')}
			>
				<span class="toggle-thumb"></span>
			</button>
		</div>

		<div class="setting-row">
			<span class="setting-label">{$_('settings.language')}</span>
			<div class="locale-pills">
				{#each LOCALES as l (l.code)}
					<button
						class="locale-pill"
						class:active={$locale === l.code}
						onclick={() => setLocale(l.code)}>{l.label}</button
					>
				{/each}
			</div>
		</div>
	</section>

	{#if $user?.role === 'admin'}
		<section class="settings-section">
			<a href="/admin/users" class="setting-link">👥 {$_('admin.users_title')}</a>
			<a href="/admin/products" class="setting-link">📦 {$_('admin.products_title')}</a>
		</section>
	{/if}

	<section class="settings-section">
		<button class="logout-btn" onclick={logout}>{$_('settings.logout')}</button>
	</section>
</main>

<style>
	.page {
		max-width: 480px;
		margin: 0 auto;
		padding: var(--space-4);
	}

	.page-header h1 {
		font-family: var(--font-display);
		font-size: var(--text-2xl);
		margin: var(--space-4) 0;
	}

	.profile-card {
		display: flex;
		align-items: center;
		gap: var(--space-4);
		padding: var(--space-4);
		background: var(--surface-raised);
		border-radius: 16px;
		margin-bottom: var(--space-4);
	}

	.avatar {
		width: 56px;
		height: 56px;
		border-radius: 50%;
		background: var(--color-primary-light);
		color: var(--color-primary);
		font-size: var(--text-xl);
		font-weight: 700;
		display: flex;
		align-items: center;
		justify-content: center;
		flex-shrink: 0;
	}

	.profile-info {
		display: flex;
		flex-direction: column;
		gap: 2px;
	}

	.profile-name {
		font-weight: 600;
		font-size: var(--text-base);
		color: var(--text-primary);
		margin: 0;
	}

	.profile-email {
		font-size: var(--text-sm);
		color: var(--text-muted);
		margin: 0;
	}

	.role-badge {
		display: inline-block;
		font-size: var(--text-xs);
		background: var(--surface-overlay);
		color: var(--text-secondary);
		padding: 2px var(--space-2);
		border-radius: 999px;
		margin-top: 4px;
	}

	.settings-section {
		background: var(--surface-raised);
		border-radius: 14px;
		padding: var(--space-2) var(--space-4);
		margin-bottom: var(--space-3);
		display: flex;
		flex-direction: column;
		gap: 0;
	}

	.setting-row {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: var(--space-3);
		min-height: 52px;
		border-bottom: 1px solid var(--border-subtle);
	}

	.setting-row:last-child {
		border-bottom: none;
	}

	.setting-label {
		font-size: var(--text-base);
		color: var(--text-primary);
	}

	/* Toggle switch */
	.toggle {
		width: 48px;
		height: 28px;
		border-radius: 14px;
		border: none;
		background: var(--border-default);
		padding: 3px;
		cursor: pointer;
		transition: background 200ms;
		display: flex;
		align-items: center;
	}

	.toggle.on {
		background: var(--color-primary);
	}

	.toggle-thumb {
		width: 22px;
		height: 22px;
		border-radius: 50%;
		background: white;
		transition: transform 200ms;
		display: block;
	}

	.toggle.on .toggle-thumb {
		transform: translateX(20px);
	}

	.locale-pills {
		display: flex;
		gap: var(--space-1);
		flex-wrap: wrap;
		justify-content: flex-end;
	}

	.locale-pill {
		padding: var(--space-1) var(--space-2);
		border-radius: 8px;
		border: 1px solid var(--border-subtle);
		background: transparent;
		color: var(--text-secondary);
		font-size: var(--text-xs);
		font-family: var(--font-body);
		cursor: pointer;
		transition: background 100ms;
	}

	.locale-pill.active {
		background: var(--color-primary-light);
		color: var(--color-primary);
		border-color: var(--color-primary);
	}

	.setting-link {
		display: flex;
		align-items: center;
		gap: var(--space-3);
		min-height: 52px;
		font-size: var(--text-base);
		color: var(--text-primary);
		text-decoration: none;
		border-bottom: 1px solid var(--border-subtle);
	}

	.setting-link:last-child {
		border-bottom: none;
	}

	.logout-btn {
		width: 100%;
		min-height: 52px;
		border: none;
		background: transparent;
		color: var(--color-danger);
		font-size: var(--text-base);
		font-family: var(--font-body);
		cursor: pointer;
		text-align: left;
	}
</style>
