// frontend/src/routes/stores/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { api } from '$lib/api';
	import { _ } from 'svelte-i18n';
	import { user } from '$lib/stores/userStore';

	interface Store {
		id: string;
		name: string;
		icon: string;
		color: string;
		address: string;
	}

	interface ShelfRow {
		category_id: string;
		position: number;
		auto_learned: boolean;
		category_name: string;
		icon: string;
		color: string;
	}

	interface Category {
		id: string;
		name_de: string;
		icon: string;
	}

	let stores = $state<Store[]>([]);
	let loading = $state(true);
	let errorMsg = $state('');

	// Bulk "assign category → store" tool (admin only).
	let categories = $state<Category[]>([]);
	let bulkCategory = $state('');
	let bulkStore = $state('');
	let bulkBusy = $state(false);
	let bulkMessage = $state('');

	async function assignByCategory() {
		if (!bulkCategory || !bulkStore) return;
		bulkBusy = true;
		bulkMessage = '';
		try {
			const res = await api.put<{ assigned: number }>('/api/products/by-category/stores', {
				category_id: bulkCategory,
				store_id: bulkStore
			});
			bulkMessage = $_('stores.bulk_done', { values: { n: res.assigned } });
		} catch {
			bulkMessage = $_('stores.bulk_error');
		} finally {
			bulkBusy = false;
		}
	}

	// Edit / create dialog
	let dialogOpen = $state(false);
	let editTarget = $state<Store | null>(null);
	let form = $state({ name: '', icon: '🛒', color: '#6366f1', address: '' });
	let saving = $state(false);

	// Shelf order editor
	let shelfStoreId = $state<string | null>(null);
	let shelfRows = $state<ShelfRow[]>([]);
	let shelfLoading = $state(false);
	let dragIndex = $state<number | null>(null);

	onMount(loadStores);

	async function loadStores() {
		loading = true;
		try {
			stores = await api.get<Store[]>('/api/stores');
			if ($user?.role === 'admin') {
				categories = await api.get<Category[]>('/api/categories').catch(() => [] as Category[]);
			}
		} catch {
			errorMsg = $_('stores.load_error');
		} finally {
			loading = false;
		}
	}

	function openCreate() {
		editTarget = null;
		form = { name: '', icon: '🛒', color: '#6366f1', address: '' };
		dialogOpen = true;
	}

	function openEdit(s: Store) {
		editTarget = s;
		form = {
			name: s.name,
			icon: s.icon || '🛒',
			color: s.color || '#6366f1',
			address: s.address || ''
		};
		dialogOpen = true;
	}

	async function saveStore() {
		if (!form.name.trim()) return;
		saving = true;
		try {
			if (editTarget) {
				await api.put(`/api/stores/${editTarget.id}`, form);
				stores = stores.map((s) => (s.id === editTarget!.id ? { ...s, ...form } : s));
			} else {
				const created = await api.post<Store>('/api/stores', form);
				stores = [...stores, created];
			}
			dialogOpen = false;
		} catch {
			errorMsg = $_('stores.save_error');
		} finally {
			saving = false;
		}
	}

	async function deleteStore(id: string) {
		if (!confirm($_('stores.confirm_delete'))) return;
		try {
			await api.delete(`/api/stores/${id}`);
			stores = stores.filter((s) => s.id !== id);
			if (shelfStoreId === id) shelfStoreId = null;
		} catch {
			errorMsg = $_('stores.delete_error');
		}
	}

	async function toggleShelf(storeId: string) {
		if (shelfStoreId === storeId) {
			shelfStoreId = null;
			return;
		}
		shelfStoreId = storeId;
		shelfLoading = true;
		try {
			shelfRows = await api.get<ShelfRow[]>(`/api/stores/${storeId}/shelf-order`);
		} catch {
			shelfRows = [];
		} finally {
			shelfLoading = false;
		}
	}

	function dragStart(i: number) {
		dragIndex = i;
	}

	function dragOver(e: DragEvent, i: number) {
		e.preventDefault();
		if (dragIndex === null || dragIndex === i) return;
		const moved = shelfRows[dragIndex];
		const next = [...shelfRows];
		next.splice(dragIndex, 1);
		next.splice(i, 0, moved);
		shelfRows = next;
		dragIndex = i;
	}

	async function saveShelfOrder() {
		if (!shelfStoreId) return;
		const payload = shelfRows.map((r, idx) => ({ category_id: r.category_id, position: idx + 1 }));
		try {
			await api.put(`/api/stores/${shelfStoreId}/shelf-order`, payload);
		} catch {
			errorMsg = $_('stores.shelf_error');
		}
	}
</script>

<div class="page">
	<header class="page-header">
		<h1>{$_('stores.title')}</h1>
		<button class="btn-primary" onclick={openCreate}>{$_('stores.add')}</button>
	</header>

	{#if errorMsg}
		<p class="error-banner">{errorMsg}</p>
	{/if}

	{#if loading}
		<p class="hint">{$_('list.loading')}</p>
	{:else if stores.length === 0}
		<div class="empty">
			<span class="empty-icon">🏪</span>
			<p>{$_('stores.empty')}</p>
			<button class="btn-primary" onclick={openCreate}>{$_('stores.create_first')}</button>
		</div>
	{:else}
		<ul class="store-list">
			{#each stores as s (s.id)}
				<li class="store-row">
					<span class="store-icon" style:background-color={s.color || '#e5e7eb'}
						>{s.icon || '🛒'}</span
					>
					<div class="store-info">
						<span class="store-name">{s.name}</span>
						{#if s.address}<span class="store-addr">{s.address}</span>{/if}
					</div>
					<div class="store-actions">
						<button
							class="icon-btn"
							onclick={() => toggleShelf(s.id)}
							aria-label={$_('stores.shelf_order')}
						>
							{shelfStoreId === s.id ? '▲' : '☰'}
						</button>
						<button class="icon-btn" onclick={() => openEdit(s)} aria-label={$_('stores.edit')}
							>✎</button
						>
						<button
							class="icon-btn danger"
							onclick={() => deleteStore(s.id)}
							aria-label={$_('stores.delete')}>✕</button
						>
					</div>
				</li>

				{#if shelfStoreId === s.id}
					<li class="shelf-panel">
						{#if shelfLoading}
							<p class="hint">{$_('list.loading')}</p>
						{:else if shelfRows.length === 0}
							<p class="hint">{$_('stores.no_categories')}</p>
						{:else}
							<p class="shelf-hint">{$_('stores.shelf_hint')}</p>
							<ul class="shelf-list">
								{#each shelfRows as row, i (row.category_id)}
									<li
										class="shelf-row"
										class:dragging={dragIndex === i}
										draggable="true"
										ondragstart={() => dragStart(i)}
										ondragover={(e) => dragOver(e, i)}
										ondragend={() => {
											dragIndex = null;
											saveShelfOrder();
										}}
									>
										<span class="drag-handle" aria-hidden="true">⠿</span>
										<span class="cat-dot" style:background-color={row.color}></span>
										<span class="cat-icon">{row.icon}</span>
										<span class="cat-name">{row.category_name}</span>
										{#if row.auto_learned}
											<span class="auto-badge">auto</span>
										{/if}
									</li>
								{/each}
							</ul>
						{/if}
					</li>
				{/if}
			{/each}
		</ul>
	{/if}

	{#if $user?.role === 'admin' && stores.length > 0 && categories.length > 0}
		<section class="bulk-tool">
			<h2 class="bulk-title">{$_('stores.bulk_title')}</h2>
			<p class="bulk-hint">{$_('stores.bulk_hint')}</p>
			<div class="bulk-row">
				<select bind:value={bulkCategory} aria-label={$_('stores.bulk_category')}>
					<option value="">{$_('stores.bulk_category')}</option>
					{#each categories as c (c.id)}
						<option value={c.id}>{c.icon} {c.name_de}</option>
					{/each}
				</select>
				<span class="bulk-arrow" aria-hidden="true">→</span>
				<select bind:value={bulkStore} aria-label={$_('stores.bulk_store')}>
					<option value="">{$_('stores.bulk_store')}</option>
					{#each stores as s (s.id)}
						<option value={s.id}>{s.icon} {s.name}</option>
					{/each}
				</select>
				<button
					class="btn-primary"
					onclick={assignByCategory}
					disabled={bulkBusy || !bulkCategory || !bulkStore}
					>{bulkBusy ? '…' : $_('stores.bulk_assign')}</button
				>
			</div>
			{#if bulkMessage}<p class="bulk-message">{bulkMessage}</p>{/if}
		</section>
	{/if}
</div>

{#if dialogOpen}
	<div class="backdrop" role="presentation" onclick={() => (dialogOpen = false)}></div>
	<div class="dialog" role="dialog" aria-modal="true">
		<h2>{editTarget ? $_('stores.form.edit') : $_('stores.form.create')}</h2>
		<label>
			{$_('stores.form.name')}
			<input type="text" bind:value={form.name} placeholder={$_('stores.form.name_ph')} />
		</label>
		<div class="row">
			<label>
				{$_('stores.form.emoji')}
				<input type="text" bind:value={form.icon} maxlength="2" class="emoji-input" />
			</label>
			<label>
				{$_('stores.form.color')}
				<input type="color" bind:value={form.color} class="color-input" />
			</label>
		</div>
		<label>
			{$_('stores.form.address')}
			<input type="text" bind:value={form.address} placeholder={$_('stores.form.address_ph')} />
		</label>
		<div class="dialog-actions">
			<button class="btn-ghost" onclick={() => (dialogOpen = false)}
				>{$_('stores.form.cancel')}</button
			>
			<button class="btn-primary" onclick={saveStore} disabled={saving || !form.name.trim()}>
				{saving ? '…' : $_('stores.form.save')}
			</button>
		</div>
	</div>
{/if}

<style>
	.page {
		padding: var(--space-4);
		max-width: 640px;
		margin: 0 auto;
	}

	.page-header {
		display: flex;
		align-items: center;
		justify-content: space-between;
		margin-bottom: var(--space-4);
	}

	.page-header h1 {
		font-family: var(--font-display);
		font-size: var(--text-2xl);
		margin: 0;
	}

	.store-list {
		list-style: none;
		padding: 0;
		margin: 0;
		display: flex;
		flex-direction: column;
		gap: 2px;
	}

	.store-row {
		display: flex;
		align-items: center;
		gap: var(--space-3);
		padding: var(--space-3);
		background: var(--surface-base);
		border-radius: 12px;
		min-height: 56px;
	}

	.store-icon {
		width: 40px;
		height: 40px;
		border-radius: 10px;
		display: flex;
		align-items: center;
		justify-content: center;
		font-size: 20px;
		flex-shrink: 0;
	}

	.store-info {
		flex: 1;
		display: flex;
		flex-direction: column;
		gap: 2px;
		min-width: 0;
	}

	.store-name {
		font-weight: 500;
		color: var(--text-primary);
		white-space: nowrap;
		overflow: hidden;
		text-overflow: ellipsis;
	}

	.store-addr {
		font-size: var(--text-xs);
		color: var(--text-muted);
		white-space: nowrap;
		overflow: hidden;
		text-overflow: ellipsis;
	}

	.store-actions {
		display: flex;
		gap: var(--space-1);
		flex-shrink: 0;
	}

	.icon-btn {
		width: 36px;
		height: 36px;
		border-radius: 8px;
		border: none;
		background: var(--surface-overlay);
		color: var(--text-secondary);
		font-size: 16px;
		cursor: pointer;
		display: flex;
		align-items: center;
		justify-content: center;
	}

	.icon-btn.danger:hover {
		color: var(--color-danger);
	}

	.shelf-panel {
		background: var(--surface-raised);
		border-radius: 12px;
		padding: var(--space-3);
		margin-top: 2px;
	}

	.shelf-hint {
		font-size: var(--text-xs);
		color: var(--text-muted);
		margin: 0 0 var(--space-2);
	}

	.shelf-list {
		list-style: none;
		padding: 0;
		margin: 0;
		display: flex;
		flex-direction: column;
		gap: 2px;
	}

	.shelf-row {
		display: flex;
		align-items: center;
		gap: var(--space-2);
		height: 44px;
		padding: 0 var(--space-2);
		background: var(--surface-base);
		border-radius: 8px;
		cursor: grab;
		user-select: none;
	}

	.shelf-row.dragging {
		opacity: 0.4;
	}

	.drag-handle {
		color: var(--text-muted);
		font-size: 18px;
	}
	.cat-dot {
		width: 8px;
		height: 8px;
		border-radius: 50%;
		flex-shrink: 0;
	}
	.cat-icon {
		font-size: 16px;
	}
	.cat-name {
		flex: 1;
		font-size: var(--text-sm);
		color: var(--text-primary);
	}

	.auto-badge {
		font-size: var(--text-xs);
		color: var(--text-muted);
		border: 1px solid var(--border-subtle);
		border-radius: 4px;
		padding: 0 4px;
	}

	.backdrop {
		position: fixed;
		inset: 0;
		background: rgba(0 0 0 / 0.4);
		z-index: 200;
	}

	.dialog {
		position: fixed;
		bottom: 0;
		left: 0;
		right: 0;
		background: var(--surface-base);
		border-radius: 20px 20px 0 0;
		padding: var(--space-6) var(--space-4) calc(var(--space-4) + env(safe-area-inset-bottom));
		z-index: 201;
		display: flex;
		flex-direction: column;
		gap: var(--space-4);
		max-width: 640px;
		margin: 0 auto;
	}

	.dialog h2 {
		font-family: var(--font-display);
		font-size: var(--text-xl);
		margin: 0;
	}

	label {
		display: flex;
		flex-direction: column;
		gap: var(--space-1);
		font-size: var(--text-sm);
		color: var(--text-secondary);
	}

	input[type='text'] {
		font-family: var(--font-body);
		font-size: var(--text-base);
		padding: var(--space-2) var(--space-3);
		border: 1px solid var(--border-subtle);
		border-radius: 10px;
		background: var(--surface-overlay);
		outline: 2px solid transparent;
		transition: outline-color 150ms;
	}

	input[type='text']:focus {
		outline-color: var(--color-primary);
	}

	.emoji-input {
		width: 60px;
		text-align: center;
	}
	.color-input {
		width: 48px;
		height: 40px;
		border-radius: 8px;
		cursor: pointer;
		padding: 2px;
	}

	.row {
		display: flex;
		gap: var(--space-4);
	}

	.dialog-actions {
		display: flex;
		gap: var(--space-3);
		justify-content: flex-end;
	}

	.btn-primary {
		height: 44px;
		padding: 0 var(--space-4);
		border-radius: 10px;
		border: none;
		background: var(--color-primary);
		color: white;
		font-family: var(--font-body);
		font-size: var(--text-base);
		font-weight: 500;
		cursor: pointer;
	}

	.btn-primary:disabled {
		opacity: 0.5;
	}

	.btn-ghost {
		height: 44px;
		padding: 0 var(--space-4);
		border-radius: 10px;
		border: 1px solid var(--border-subtle);
		background: transparent;
		color: var(--text-secondary);
		font-family: var(--font-body);
		font-size: var(--text-base);
		cursor: pointer;
	}

	.empty {
		display: flex;
		flex-direction: column;
		align-items: center;
		gap: var(--space-3);
		padding: var(--space-16) var(--space-4);
		text-align: center;
		color: var(--text-muted);
	}

	.empty-icon {
		font-size: 48px;
	}

	.hint {
		text-align: center;
		color: var(--text-muted);
		padding: var(--space-6);
		font-size: var(--text-sm);
	}

	.error-banner {
		background: color-mix(in srgb, var(--color-danger) 10%, transparent);
		color: var(--color-danger);
		border-radius: 10px;
		padding: var(--space-3);
		font-size: var(--text-sm);
		margin-bottom: var(--space-3);
	}

	.bulk-tool {
		margin-top: var(--space-6);
		padding: var(--space-4);
		background: var(--surface-raised);
		border-radius: 12px;
	}

	.bulk-title {
		font-family: var(--font-display);
		font-size: var(--text-lg);
		margin: 0 0 var(--space-1);
	}

	.bulk-hint {
		font-size: var(--text-xs);
		color: var(--text-muted);
		margin: 0 0 var(--space-3);
	}

	.bulk-row {
		display: flex;
		align-items: center;
		gap: var(--space-2);
		flex-wrap: wrap;
	}

	.bulk-row select {
		flex: 1;
		min-width: 120px;
		font-family: var(--font-body);
		font-size: var(--text-sm);
		padding: var(--space-2) var(--space-3);
		border: 1px solid var(--border-subtle);
		border-radius: 10px;
		background: var(--surface-overlay);
		color: var(--text-primary);
	}

	.bulk-arrow {
		color: var(--text-muted);
	}

	.bulk-message {
		font-size: var(--text-sm);
		color: var(--text-secondary);
		margin: var(--space-3) 0 0;
	}
</style>

// frontend/src/pages/Stores.tsx
// Stores.tsx — store-management screen: list/create/edit/delete stores,
// per-store shelf-order (drag to reorder categories), and an admin-only
// bulk tool to assign all products of a category to a store.
import { useCallback, useEffect, useState, type CSSProperties } from 'react';
import {
  DndContext,
  closestCenter,
  PointerSensor,
  useSensor,
  useSensors,
  type DragEndEvent,
} from '@dnd-kit/core';
import {
  SortableContext,
  verticalListSortingStrategy,
  arrayMove,
  useSortable,
} from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import { api, ApiError } from '../lib/api';
import { Icon } from '../components/Icon';
import type { Store, Category } from '../lib/types';
import { useUserStore } from '../stores/userStore';
import { useTranslation } from 'react-i18next';

// ── local types not in lib/types ──
interface ShelfRow {
  category_id: string;
  position: number;
  auto_learned: boolean;
  category_name: string;
  icon: string;
  color: string;
}

interface StoreForm {
  name: string;
  icon: string;
  color: string;
  address: string;
}

const EMPTY_FORM: StoreForm = { name: '', icon: '🛒', color: '#6366f1', address: '' };

// ── shared inline styles ──
const card: CSSProperties = {
  background: 'var(--surface-raised)',
  borderRadius: 16,
  border: '1px solid var(--border-subtle)',
  boxShadow: 'var(--shadow-sm)',
};

const primaryBtn: CSSProperties = {
  background: 'var(--accent)',
  color: '#fff',
  border: 'none',
  borderRadius: 12,
  padding: '12px 18px',
  fontSize: 15,
  fontWeight: 600,
  cursor: 'pointer',
};

const ghostBtn: CSSProperties = {
  background: 'var(--surface-overlay)',
  color: 'var(--text-secondary)',
  border: '1px solid var(--border-subtle)',
  borderRadius: 12,
  padding: '10px 14px',
  fontSize: 14,
  fontWeight: 600,
  cursor: 'pointer',
  display: 'inline-flex',
  alignItems: 'center',
  gap: 6,
};

const iconBtn: CSSProperties = {
  width: 40,
  height: 40,
  display: 'inline-flex',
  alignItems: 'center',
  justifyContent: 'center',
  borderRadius: 10,
  border: '1px solid var(--border-subtle)',
  background: 'var(--surface-overlay)',
  color: 'var(--text-secondary)',
  cursor: 'pointer',
};

const inputStyle: CSSProperties = {
  width: '100%',
  boxSizing: 'border-box',
  padding: '11px 13px',
  borderRadius: 12,
  border: '1px solid var(--border-default)',
  background: 'var(--surface-base)',
  color: 'var(--text-primary)',
  fontSize: 15,
};

const labelStyle: CSSProperties = {
  display: 'block',
  fontSize: 13,
  fontWeight: 600,
  color: 'var(--text-secondary)',
  marginBottom: 6,
};

export default function StoresPage() {
  const { t } = useTranslation();
  const user = useUserStore((s) => s.user);
  const isAdmin = user?.role === 'admin';

  const [stores, setStores] = useState<Store[]>([]);
  const [categories, setCategories] = useState<Category[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  // dialog state
  const [dialogOpen, setDialogOpen] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [form, setForm] = useState<StoreForm>(EMPTY_FORM);
  const [saving, setSaving] = useState(false);

  // shelf-order state (per expanded store)
  const [expandedStore, setExpandedStore] = useState<string | null>(null);
  const [shelf, setShelf] = useState<ShelfRow[]>([]);
  const [shelfLoading, setShelfLoading] = useState(false);

  // bulk-assign state
  const [bulkCategory, setBulkCategory] = useState('');
  const [bulkStore, setBulkStore] = useState('');
  const [bulkBusy, setBulkBusy] = useState(false);
  const [bulkMsg, setBulkMsg] = useState<string | null>(null);

  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 5 } }));

  const loadStores = useCallback(async () => {
    const data = await api.get<Store[]>('/api/stores');
    setStores(data);
  }, []);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      setLoading(true);
      setError(false);
      try {
        const data = await api.get<Store[]>('/api/stores');
        if (cancelled) return;
        setStores(data);
        if (isAdmin) {
          try {
            const cats = await api.get<Category[]>('/api/categories');
            if (!cancelled) setCategories(cats);
          } catch {
            if (!cancelled) setCategories([]);
          }
        }
      } catch {
        if (!cancelled) setError(true);
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [isAdmin]);

  // ── dialog helpers ──
  function openCreate() {
    setEditingId(null);
    setForm(EMPTY_FORM);
    setDialogOpen(true);
  }

  function openEdit(s: Store) {
    setEditingId(s.id);
    setForm({
      name: s.name,
      icon: s.icon ?? '🛒',
      color: s.color ?? '#6366f1',
      address: s.address ?? '',
    });
    setDialogOpen(true);
  }

  async function saveStore() {
    if (!form.name.trim()) return;
    setSaving(true);
    const body = {
      name: form.name.trim(),
      icon: form.icon,
      color: form.color,
      address: form.address.trim(),
    };
    try {
      if (editingId) {
        await api.put<Store>(`/api/stores/${editingId}`, body);
      } else {
        await api.post<Store>('/api/stores', body);
      }
      await loadStores();
      setDialogOpen(false);
    } catch {
      alert(t('stores.save_error'));
    } finally {
      setSaving(false);
    }
  }

  async function deleteStore(s: Store) {
    if (!window.confirm(t('stores.confirm_delete'))) return;
    try {
      await api.delete<void>(`/api/stores/${s.id}`);
      if (expandedStore === s.id) setExpandedStore(null);
      await loadStores();
    } catch {
      alert(t('stores.delete_error'));
    }
  }

  // ── shelf order ──
  async function toggleShelf(storeId: string) {
    if (expandedStore === storeId) {
      setExpandedStore(null);
      return;
    }
    setExpandedStore(storeId);
    setShelf([]);
    setShelfLoading(true);
    try {
      const rows = await api.get<ShelfRow[]>(`/api/stores/${storeId}/shelf-order`);
      setShelf(rows);
    } catch {
      setShelf([]);
    } finally {
      setShelfLoading(false);
    }
  }

  async function onShelfDragEnd(storeId: string, ev: DragEndEvent) {
    const { active, over } = ev;
    if (!over || active.id === over.id) return;
    const oldIndex = shelf.findIndex((r) => r.category_id === active.id);
    const newIndex = shelf.findIndex((r) => r.category_id === over.id);
    if (oldIndex < 0 || newIndex < 0) return;
    const previous = shelf;
    const reordered = arrayMove(shelf, oldIndex, newIndex);
    setShelf(reordered);
    const payload = reordered.map((row, idx) => ({
      category_id: row.category_id,
      position: idx + 1,
    }));
    try {
      await api.put<void>(`/api/stores/${storeId}/shelf-order`, payload);
    } catch {
      setShelf(previous); // revert so the UI doesn't diverge from the server
      alert(t('stores.shelf_error'));
    }
  }

  // ── bulk assign ──
  async function bulkAssign() {
    if (!bulkCategory || !bulkStore) return;
    setBulkBusy(true);
    setBulkMsg(null);
    try {
      const result = await api.put<{ assigned: number }>('/api/products/by-category/stores', {
        category_id: bulkCategory,
        store_id: bulkStore,
      });
      setBulkMsg(t('stores.bulk_done', { n: result.assigned }));
    } catch (e) {
      void (e instanceof ApiError);
      setBulkMsg(t('stores.bulk_error'));
    } finally {
      setBulkBusy(false);
    }
  }

  // ── render ──
  if (loading) {
    return (
      <div style={{ padding: 24, textAlign: 'center', color: 'var(--text-muted)' }}>
        {t('list.loading')}
      </div>
    );
  }

  return (
    <div
      style={{ background: 'var(--surface-base)', minHeight: '100%', padding: '16px 14px 96px' }}
    >
      {/* header */}
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          marginBottom: 16,
        }}
      >
        <h1
          className="ff-display"
          style={{ margin: 0, fontSize: 24, color: 'var(--text-primary)' }}
        >
          {t('stores.title')}
        </h1>
        <button
          type="button"
          style={{ ...primaryBtn, display: 'inline-flex', alignItems: 'center', gap: 6 }}
          onClick={openCreate}
        >
          <Icon name="plus" size={18} strokeWidth={2.2} />
          {t('stores.add')}
        </button>
      </div>

      {error && (
        <div
          style={{
            ...card,
            background: 'var(--accent-light)',
            border: '1px solid var(--border-default)',
            color: 'var(--text-primary)',
            padding: '12px 14px',
            marginBottom: 14,
            fontSize: 14,
          }}
        >
          {t('stores.load_error')}
        </div>
      )}

      {/* empty state */}
      {!error && stores.length === 0 && (
        <div
          style={{
            ...card,
            padding: '40px 20px',
            textAlign: 'center',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            gap: 14,
          }}
        >
          <div style={{ color: 'var(--text-muted)' }}>
            <Icon name="store" size={56} strokeWidth={1.4} />
          </div>
          <div style={{ color: 'var(--text-secondary)', fontSize: 15 }}>{t('stores.empty')}</div>
          <button type="button" style={primaryBtn} onClick={openCreate}>
            {t('stores.create_first')}
          </button>
        </div>
      )}

      {/* store list */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
        {stores.map((s) => {
          const expanded = expandedStore === s.id;
          return (
            <div key={s.id} style={card}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 12, padding: 14 }}>
                <div
                  style={{
                    width: 50,
                    height: 50,
                    borderRadius: 15,
                    flexShrink: 0,
                    display: 'grid',
                    placeItems: 'center',
                    fontSize: 24,
                    color: '#fff',
                    background: `linear-gradient(150deg, ${s.color || 'var(--accent)'}, color-mix(in oklab, ${s.color || '#6366f1'} 72%, black))`,
                    boxShadow: `0 6px 14px color-mix(in oklab, ${s.color || '#6366f1'} 36%, transparent)`,
                  }}
                >
                  {s.icon ? s.icon : <Icon name="store" size={26} strokeWidth={1.9} />}
                </div>
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div
                    style={{
                      fontSize: 16,
                      fontWeight: 600,
                      color: 'var(--text-primary)',
                      whiteSpace: 'nowrap',
                      overflow: 'hidden',
                      textOverflow: 'ellipsis',
                    }}
                  >
                    {s.name}
                  </div>
                  {s.address && (
                    <div
                      style={{
                        fontSize: 13,
                        color: 'var(--text-muted)',
                        whiteSpace: 'nowrap',
                        overflow: 'hidden',
                        textOverflow: 'ellipsis',
                      }}
                    >
                      {s.address}
                    </div>
                  )}
                </div>
                <button
                  type="button"
                  style={iconBtn}
                  aria-label={t('stores.form.edit')}
                  onClick={() => openEdit(s)}
                >
                  <Icon name="pencil" size={18} />
                </button>
                <button
                  type="button"
                  style={iconBtn}
                  aria-label="delete"
                  onClick={() => deleteStore(s)}
                >
                  <Icon name="trash" size={18} />
                </button>
              </div>

              <div style={{ padding: '0 14px 14px' }}>
                <button
                  type="button"
                  style={{ ...ghostBtn, width: '100%', justifyContent: 'space-between' }}
                  onClick={() => toggleShelf(s.id)}
                >
                  <span style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}>
                    <Icon name="sliders" size={16} />
                    {t('stores.shelf_order')}
                  </span>
                  <span
                    style={{
                      display: 'inline-flex',
                      transition: 'transform 150ms',
                      transform: expanded ? 'rotate(180deg)' : 'none',
                    }}
                  >
                    <Icon name="chevron-down" size={18} />
                  </span>
                </button>

                {expanded && (
                  <div style={{ marginTop: 12 }}>
                    <div style={{ fontSize: 13, color: 'var(--text-muted)', marginBottom: 10 }}>
                      {t('stores.shelf_hint')}
                    </div>
                    {shelfLoading ? (
                      <div style={{ color: 'var(--text-muted)', fontSize: 14, padding: '8px 0' }}>
                        {t('list.loading')}
                      </div>
                    ) : shelf.length === 0 ? (
                      <div style={{ color: 'var(--text-muted)', fontSize: 14, padding: '8px 0' }}>
                        {t('stores.no_categories')}
                      </div>
                    ) : (
                      <DndContext
                        sensors={sensors}
                        collisionDetection={closestCenter}
                        onDragEnd={(ev) => onShelfDragEnd(s.id, ev)}
                      >
                        <SortableContext
                          items={shelf.map((r) => r.category_id)}
                          strategy={verticalListSortingStrategy}
                        >
                          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                            {shelf.map((row) => (
                              <ShelfItem
                                key={row.category_id}
                                row={row}
                                autoLabel={t('stores.auto')}
                              />
                            ))}
                          </div>
                        </SortableContext>
                      </DndContext>
                    )}
                  </div>
                )}
              </div>
            </div>
          );
        })}
      </div>

      {/* admin bulk tool */}
      {isAdmin && stores.length > 0 && categories.length > 0 && (
        <div style={{ ...card, padding: 16, marginTop: 18 }}>
          <h2
            className="ff-display"
            style={{ margin: '0 0 4px', fontSize: 18, color: 'var(--text-primary)' }}
          >
            {t('stores.bulk_title')}
          </h2>
          <div style={{ fontSize: 13, color: 'var(--text-muted)', marginBottom: 14 }}>
            {t('stores.bulk_hint')}
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            <select
              style={inputStyle}
              value={bulkCategory}
              onChange={(e) => setBulkCategory(e.target.value)}
            >
              <option value="">{t('stores.bulk_category')}</option>
              {categories.map((c) => (
                <option key={c.id} value={c.id}>
                  {c.name_de}
                </option>
              ))}
            </select>
            <select
              style={inputStyle}
              value={bulkStore}
              onChange={(e) => setBulkStore(e.target.value)}
            >
              <option value="">{t('stores.bulk_store')}</option>
              {stores.map((s) => (
                <option key={s.id} value={s.id}>
                  {s.name}
                </option>
              ))}
            </select>
            <button
              type="button"
              style={{ ...primaryBtn, opacity: bulkBusy || !bulkCategory || !bulkStore ? 0.6 : 1 }}
              disabled={bulkBusy || !bulkCategory || !bulkStore}
              onClick={bulkAssign}
            >
              {t('stores.bulk_assign')}
            </button>
            {bulkMsg && (
              <div style={{ fontSize: 14, color: 'var(--text-secondary)' }}>{bulkMsg}</div>
            )}
          </div>
        </div>
      )}

      {/* create/edit dialog */}
      {dialogOpen && (
        <div
          role="presentation"
          onClick={() => !saving && setDialogOpen(false)}
          style={{
            position: 'fixed',
            inset: 0,
            background: 'rgba(0,0,0,0.4)',
            display: 'flex',
            alignItems: 'flex-end',
            justifyContent: 'center',
            zIndex: 50,
          }}
        >
          <div
            role="dialog"
            aria-modal="true"
            onClick={(e) => e.stopPropagation()}
            style={{
              background: 'var(--surface-raised)',
              width: '100%',
              maxWidth: 480,
              borderTopLeftRadius: 20,
              borderTopRightRadius: 20,
              boxShadow: 'var(--shadow-lg)',
              padding: 20,
              boxSizing: 'border-box',
            }}
          >
            <div
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
                marginBottom: 16,
              }}
            >
              <h2
                className="ff-display"
                style={{ margin: 0, fontSize: 20, color: 'var(--text-primary)' }}
              >
                {editingId ? t('stores.form.edit') : t('stores.form.create')}
              </h2>
              <button
                type="button"
                style={iconBtn}
                aria-label={t('stores.form.cancel')}
                onClick={() => setDialogOpen(false)}
              >
                <Icon name="x" size={18} />
              </button>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
              <div>
                <label style={labelStyle}>{t('stores.form.name')}</label>
                <input
                  style={inputStyle}
                  value={form.name}
                  placeholder={t('stores.form.name_ph')}
                  onChange={(e) => setForm((f) => ({ ...f, name: e.target.value }))}
                />
              </div>

              <div style={{ display: 'flex', gap: 12 }}>
                <div style={{ flex: 1 }}>
                  <label style={labelStyle}>{t('stores.form.emoji')}</label>
                  <input
                    style={{ ...inputStyle, textAlign: 'center', fontSize: 22 }}
                    value={form.icon}
                    maxLength={2}
                    onChange={(e) => setForm((f) => ({ ...f, icon: e.target.value }))}
                  />
                </div>
                <div style={{ flex: 1 }}>
                  <label style={labelStyle}>{t('stores.form.color')}</label>
                  <input
                    type="color"
                    style={{ ...inputStyle, height: 46, padding: 4 }}
                    value={form.color}
                    onChange={(e) => setForm((f) => ({ ...f, color: e.target.value }))}
                  />
                </div>
              </div>

              <div>
                <label style={labelStyle}>{t('stores.form.address')}</label>
                <input
                  style={inputStyle}
                  value={form.address}
                  placeholder={t('stores.form.address_ph')}
                  onChange={(e) => setForm((f) => ({ ...f, address: e.target.value }))}
                />
              </div>

              <div style={{ display: 'flex', gap: 10, marginTop: 4 }}>
                <button
                  type="button"
                  style={{ ...ghostBtn, flex: 1, justifyContent: 'center' }}
                  disabled={saving}
                  onClick={() => setDialogOpen(false)}
                >
                  {t('stores.form.cancel')}
                </button>
                <button
                  type="button"
                  style={{ ...primaryBtn, flex: 1, opacity: saving || !form.name.trim() ? 0.6 : 1 }}
                  disabled={saving || !form.name.trim()}
                  onClick={saveStore}
                >
                  {t('stores.form.save')}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// ── sortable shelf row ──
function ShelfItem({ row, autoLabel }: { row: ShelfRow; autoLabel: string }) {
  const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({
    id: row.category_id,
  });
  const style: CSSProperties = {
    transform: CSS.Transform.toString(transform),
    transition,
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '10px 12px',
    borderRadius: 12,
    border: '1px solid var(--border-subtle)',
    background: 'var(--surface-overlay)',
    boxShadow: isDragging ? 'var(--shadow-md)' : 'none',
    opacity: isDragging ? 0.9 : 1,
    cursor: 'grab',
    touchAction: 'none',
  };
  return (
    <div ref={setNodeRef} style={style} {...attributes} {...listeners}>
      <span
        style={{ width: 12, height: 12, borderRadius: '50%', background: row.color, flexShrink: 0 }}
      />
      <span style={{ fontSize: 18 }}>{row.icon}</span>
      <span style={{ flex: 1, fontSize: 15, color: 'var(--text-primary)' }}>
        {row.category_name}
      </span>
      {row.auto_learned && (
        <span
          style={{
            fontSize: 11,
            fontWeight: 700,
            textTransform: 'uppercase',
            letterSpacing: 0.5,
            color: 'var(--accent-600)',
            background: 'var(--accent-light)',
            padding: '3px 8px',
            borderRadius: 999,
          }}
        >
          {autoLabel}
        </span>
      )}
    </div>
  );
}
