// frontend/src/components/BarcodeScanner.tsx
// BarcodeScanner.tsx — full-screen camera overlay, ported from the Svelte
// component. Dynamically imports @zxing/browser (kept out of the main bundle),
// prefers the rear camera, and reports decoded text via onScan.
//
// TODO: The scanner redesign (result/edit/unknown sheets, reticle animation,
// torch toggle) was reverted because it drifted from the design-ref. When
// re-implementing, use createPortal(…, document.body) so the overlay escapes
// the AddBar's positioned/overflow ancestors and renders truly full-screen.
// Refer to design-ref/ and the revert commit for what the previous attempt did.
import { useEffect, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Icon } from './Icon';

export function BarcodeScanner({
  onScan,
  onClose,
}: {
  onScan: (code: string) => void;
  onClose: () => void;
}) {
  const { t } = useTranslation();
  const videoRef = useRef<HTMLVideoElement>(null);
  const [error, setError] = useState(false);

  useEffect(() => {
    let controls: { stop: () => void } | null = null;
    let cancelled = false;

    (async () => {
      try {
        const { BrowserMultiFormatReader } = await import('@zxing/browser');
        const reader = new BrowserMultiFormatReader();
        if (cancelled || !videoRef.current) return;
        controls = await reader.decodeFromVideoDevice(undefined, videoRef.current, (result) => {
          if (result) onScan(result.getText());
        });
      } catch {
        if (!cancelled) setError(true);
      }
    })();

    return () => {
      cancelled = true;
      controls?.stop();
    };
  }, [onScan]);

  return (
    <div
      style={{
        position: 'absolute',
        inset: 0,
        zIndex: 300,
        background: '#000',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
      }}
      role="dialog"
      aria-label={t('scanner.aria_label')}
    >
      <video
        ref={videoRef}
        style={{ width: '100%', height: '100%', objectFit: 'cover' }}
        muted
        playsInline
      />
      <div
        style={{
          position: 'absolute',
          width: 250,
          height: 250,
          border: '3px solid var(--accent)',
          borderRadius: 16,
          boxShadow: '0 0 0 9999px rgba(0,0,0,0.45)',
        }}
      />
      <div
        style={{ position: 'absolute', bottom: 120, color: '#fff', fontSize: 15, fontWeight: 600 }}
      >
        {error ? t('scanner.camera_unavailable') : t('scanner.scanning')}
      </div>
      <button
        onClick={onClose}
        style={{
          position: 'absolute',
          top: 'calc(16px + env(safe-area-inset-top))',
          left: 16,
          display: 'flex',
          alignItems: 'center',
          gap: 6,
          padding: '10px 14px',
          borderRadius: 12,
          border: 'none',
          background: 'rgba(255,255,255,0.16)',
          color: '#fff',
          fontSize: 15,
          fontWeight: 600,
          cursor: 'pointer',
        }}
      >
        <Icon name="x" size={18} />
        {t('scanner.cancel')}
      </button>
    </div>
  );
}

// frontend/src/lib/components/BarcodeScanner.svelte
<script lang="ts">
	import { onMount, onDestroy } from 'svelte';
	import { browser } from '$app/environment';
	import { _ } from 'svelte-i18n';

	interface Props {
		onScan?: (barcode: string) => void;
		onClose?: () => void;
	}
	let { onScan, onClose }: Props = $props();

	let videoEl: HTMLVideoElement | undefined = $state();
	let error = $state('');

	// Dynamically import @zxing/browser to avoid SSR issues.
	let controls: { stop: () => void } | undefined;

	onMount(async () => {
		if (!browser) return;
		const { BrowserMultiFormatReader } = await import('@zxing/browser');
		const reader = new BrowserMultiFormatReader();

		try {
			const devices = await BrowserMultiFormatReader.listVideoInputDevices();
			// Prefer rear camera on mobile.
			const deviceId =
				devices.find((d) => /back|rear|environment/i.test(d.label))?.deviceId ??
				devices[0]?.deviceId;

			if (!videoEl) return;
			controls = await reader.decodeFromVideoDevice(deviceId, videoEl, (result, err) => {
				if (result) {
					onScan?.(result.getText());
				} else if (err && !(err instanceof Error && err.name === 'NotFoundException')) {
					// NotFoundException fires on every frame with no barcode — expected
					console.warn('scanner:', err);
				}
			});
		} catch (e) {
			error = $_('scanner.camera_unavailable');
			console.error('barcode scanner init:', e);
		}
	});

	onDestroy(() => {
		controls?.stop();
	});
</script>

<div class="scanner-overlay" role="dialog" aria-modal="true" aria-label={$_('scanner.aria_label')}>
	<button class="cancel" onclick={onClose}>{$_('scanner.cancel')}</button>
	<video bind:this={videoEl} autoplay playsinline muted></video>
	{#if error}
		<p class="error-msg">{error}</p>
	{:else}
		<div class="scan-window" aria-hidden="true"></div>
		<p class="hint">{$_('scanner.scanning')}</p>
	{/if}
</div>

<style>
	.scanner-overlay {
		position: fixed;
		inset: 0;
		background: #000;
		z-index: 300;
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
	}

	video {
		position: absolute;
		inset: 0;
		width: 100%;
		height: 100%;
		object-fit: cover;
	}

	.scan-window {
		position: relative;
		width: 250px;
		height: 250px;
		border-radius: 16px;
		border: 2px solid var(--color-primary);
		box-shadow: 0 0 0 9999px rgba(0 0 0 / 0.6);
	}

	.cancel {
		position: absolute;
		top: calc(var(--space-4) + env(safe-area-inset-top));
		left: var(--space-4);
		background: transparent;
		border: none;
		color: white;
		font-size: var(--text-base);
		cursor: pointer;
		z-index: 1;
		min-height: 48px;
		padding: 0 var(--space-2);
	}

	.hint {
		position: relative;
		color: white;
		margin-top: var(--space-4);
		font-size: var(--text-sm);
	}

	.error-msg {
		position: relative;
		color: #fca5a5;
		font-size: var(--text-sm);
		text-align: center;
		padding: var(--space-4);
	}
</style>
